### ISSUE TITLE
Patch Order is using Sort Order Option

### ISSUE THREAD

**Issue by amerryma** [Masquerade-Circus/mongoose-history-plugin#19]
I noticed something kind of strange. I wanted to make sure this was intended. The following code basically passes a sort option through the getDiff function which pulls histories from the database in the order specified:

https://github.com/Masquerade-Circus/mongoose-history-plugin/blob/7d7a111f8d240f02680444cbeb0e0404e74c8d12/index.js#L377

The patch order then uses the order returned from the DB to do the patching. This leads to some pretty strange results, which is rather unintuitive in my eyes. I could see it being useful in some very specific edge cases but don't think this should be the default pattern. 

Shouldn't the sort always be timestamp, then the order is reapplied after?

**Comment by alexstaroselsky** [comment]
I'm seeing something along the same lines regarding the [getPreviousVersion](https://github.com/Masquerade-Circus/mongoose-history-plugin/blob/7d7a111f8d240f02680444cbeb0e0404e74c8d12/index.js#L121-L127) when any version greater than 1.0.0 is being saved/compared. [getVersions](https://github.com/Masquerade-Circus/mongoose-history-plugin/blob/7d7a111f8d240f02680444cbeb0e0404e74c8d12/index.js#L376-L396) returns an array of versions, always starting with version `0.0.0`.  `versions[0]` resolves to `0.0.0` so if version `2.0.0` is about to be saved (given `0.0.0 and `1.0.0` exist), `let previousVersion = await getPreviousVersion(currentDocument);` is comparing it to version `0.0.0` instead of version `1.0.0`. In the case of something like comparing an array of reference ObjectID values that have different lengths between each version (increasing amount), it leads to duplicate reference ObjectID as the patch has extra additions between `0.0.0` and `2.0.0`.

**Comment by Masquerade-Circus** [comment]
Resolved by #21
